# This configuration file takes effect when the project's "Analysis method"
# on SonarQube cloud is set to "Automatic analysis".
#
# Automatic analysis has limitations according to the documentation at
# https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/automatic-analysis
# - Branch analysis (analysis of non-pull request branches other than main
#   branch) is not supported.
# - Automatic analysis does not support monorepos (the monorepo strategy).
# - Code coverage information is not supported.
# - Import of external rule engine reports is not supported.
# - Automatic analysis logs are not available.
# - If you experience prolonged analysis times or need to review the analysis
#   logs, consider onboarding your project using a CI-based analysis.
#
# Available options that can be set in this file are listed on the project's
# "Administration" -> "Analysis method" page.

# Path to sources
#sonar.sources=
sonar.exclusions=vendor/**/*,tests/**/*
#sonar.inclusions=

# Path to tests
sonar.tests=tests
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
