name: Keep Cache

on:
  workflow_dispatch:
  schedule:
  - cron: "36 4 * * 1,3,6"

jobs:
  keep-ubuntu-caches:
    name: Keep Ubuntu Build Caches
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        build-type: [ "release", "debug" ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Load Ubuntu Build Caches
      uses: actions/cache/restore@v6
      with:
        path: ccache
        key: ccache-${{ matrix.build-type }}-${{ matrix.os }}-${{ github.ref }}
        restore-keys: |
          ccache-${{ matrix.build-type }}-${{ matrix.os }}-

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@7a9194bad497f0b993708eeaf10fc0a2d726eb71
